### ISSUE TITLE
Tampermonkey support?

### ISSUE THREAD

**Issue by Osahashi** [krisu5/userstyles#1]
I tried to install the script on my Tampermonkey but it didn't work, does it not have support for it? Installation via URL doesn't work on my Firefox, it says "invalid user script".

**Comment by krisu5** [comment]
Tampermonkey doesn't support UserCSS / userstyles, it only supports user**scripts** (those are javascript).

[AniList - Anti-Social](https://greasyfork.org/en/scripts/397799-anilist-anti-social) and [Imgur - Minimal Design for non-Imgurians](https://greasyfork.org/en/scripts/398960-imgur-minimal-design-for-non-imgurians) on the GreasyFork has userscript version (click "Install this script").

For [DuckDuckGo - Wider, Prettier and Customizable](https://github.com/krisu5/userstyles/tree/master/DuckDuckGo%20-%20Wider%20Prettier%20and%20Customizable) and [Twitter - Clean 2019 Design (Now With Light Blue™)](https://github.com/krisu5/userstyles/tree/master/Twitter%20-%20Clean%202019%20Design%20(Now%20With%20Light%20Blue)), there's no userscript versions for technical reasons.

You need to install [Stylus](https://github.com/openstyles/stylus#releases) (userstyles manager) for those styles.
