### ISSUE TITLE
Does this support multiple images in the same page?

### ISSUE THREAD

**Issue by DonaldTsang** [krisu5/userstyles#2]
Take a look at https://greasyfork.org/en/scripts/12444-imgur-load-remaining-images-automatically in comparison

**Comment by krisu5** [comment]
I wouldn't see why it wouldn't work.

Userstyles are just CSS, they (usually) don't intervene with other userscripts (those are javascript), unless it's something style related.

**But**, that specific script doesn't work on 2020 redesign. It wouldn't work regardless if you use this style or not, unless it works on the older design.
