### ISSUE TITLE
A problem using Anilist anti social extras 

### ISSUE THREAD

**Issue by masdeuss** [krisu5/userstyles#4]
i have both the scripts anilist anti social and its extras. while using it i saw a problem that when extras is on the section where openings and endings are listed doesn't appear. since this section is not a social section i would like to use it as well. please fix this.
Thanks in advance.

**Comment by krisu5** [comment]
Link where issue occurs would be nice.

Couldn't pinpoint the problem by myself.

**Comment by masdeuss** [comment]
Without using the extras script:
![image](https://user-images.githubusercontent.com/82696882/115117510-5ee81900-9fb8-11eb-843d-af7f4a0e0c17.png)
-----------------------
With the script on:
![image](https://user-images.githubusercontent.com/82696882/115117539-82ab5f00-9fb8-11eb-9f76-5ab91dd8784d.png)
----------------------

**Comment by krisu5** [comment]
**Link to the page** where issue occurs, not screenshots.

**Comment by krisu5** [comment]
Well I found the issue you were talking about after all, but it's not userCSS or userscript's fault.

It's a bug on Anilist.

Even when both of the styles are disabled (or using different browser), this still happens. Usually when refreshing the page or other means (like going to the page from URL).

Sections show up again if you go to the anime page from different AniList page (eg. https://anilist.co/staff/152601 -> click "JoJo no Kimyou na Bouken").

I also checked the HTML code and whole opening / ending section is completely gone from the code, which isn't possible to do with CSS.

You should report this to the [AniList's "bug reports" forum](https://anilist.co/forum/recent?category=12).
